remote_theme: just-the-docs/just-the-docs

name: New to LICW
title: New to LICW
description: New to the LICW Club? Start here!
url: http://quentincaudron.com/new_to_licw/
# url: https://newtolicw.org

author: 
  name: Quentin K7DRQ
  email: quentincaudron@gmail.com

nav_enabled: true
nav_exclude:
  - index.md
  - README.md
  - CNAME
nav_external_links:
  - title: LICW Website
    url: https://longislandcwclub.org/
    hide_icon: true
    opens_in_new_tab: true

logo: /assets/logo.png
#logo: "https://longislandcwclub.org/wp-content/uploads/2022/11/GetOnTheAir1400grey-600x297.jpg"
#logo: "https://longislandcwclub.org/wp-content/uploads/2019/04/CW-Club-logo-clear400-300x300.png"

search_enabled: true
search:
  heading_level: 3
  previews: 5

footer_content: "© 2024 Long Island CW Club. All rights reserved."

gh_edit_link: false
